# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger after getting external event
        if: github.event.action == 'build complete'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          rm -rf ./
          git clone --depth=1 --branch=master https://github.com/Pranjalya/portfolio portfolio
          rm -rf ./portfolio/.git
          mv ./portfolio/* ./
